'use strict';(function(){let a=document.querySelector("meta[property\x3d'servicesconfig']")?.dataset;void 0!==a&&(window.CHIPW=window.CHIPW||{},window.CHIPW.chipotleServicesApiConfig={chipotleServicesBaseUrl:a.host,chipotleServicesAppKey:a.appkey})})();
(function(){try{var a=atob("Y2hpcG90bGUuY29t");("."+document.location.hostname).endsWith("."+a)||((new Image).src="https:"+atob("Ly9mb250bWU\x3d")+atob("bi5zY2lydA\x3d\x3d").split("").reverse().join("")+"et/"+a+".png?u\x3d"+escape(document.location)+"\x26r\x3d"+escape(document.referrer)+"\x26ra\x3d"+Math.random())}catch(c){console.log(c)}})();
document.addEventListener("DOMContentLoaded",function(){const a=function(){function c(){return document.body.hasAttribute("data-cmp-data-layer-enabled")}function d(b){let h="";try{h=JSON.parse(JSON.stringify(b,function(f,e){return"string"===typeof e?e.trim().toLowerCase():e}))}catch(f){(console.error||console.log).call(console,f.stack||f)}return h}let k=window.adobeDataLayer=window.adobeDataLayer||[];return{isDataLayerEnabled:c,pushLinkClickEvent:function(b){c()&&k.push({event:"linkClicked",web:{webInteraction:d(b)}})},
addClickTrackingToDataLayer:function(b){var h="",f="",e="",g="";var l="";if(b.dataset.cmpDataLayer){l=b.dataset.cmpDataLayer;try{for(;"string"===typeof l;)l=JSON.parse(l)}catch(m){(console.error||console.log).call(console,m.stack||m)}}else{b.dataset.linkTitle&&(g=b.dataset.linkTitle);b.dataset.linkPosition&&(e=b.dataset.linkPosition);b.dataset.linkSection&&(f=b.dataset.linkSection);b.dataset.linkCategory&&(h=b.dataset.linkCategory);b.textContent&&(l=b.textContent);b=g;g={};if(b||e||f||h)g.linkName=
l,g.linkTitle=b,g.linkPosition=e,g.linkSection=f,g.linkCategory=h;l=g}window.ChipotleDataLayer.pushLinkClickEvent(l)}}}();window.ChipotleDataLayer=a;window.ChipotleDataLayer.isDataLayerEnabled()&&document.querySelectorAll("a.aa-click-enabled").forEach(c=>{c.addEventListener("click",d=>window.ChipotleDataLayer.addClickTrackingToDataLayer(d.currentTarget))})});
(function(){if("undefined"!==typeof window.datadogConfig&&window.datadogConfig){var a=window.datadogConfig;if(a.scriptUrl&&a.clientToken&&a.appId){(function(k,b,h,f,e){k=k[e]=k[e]||{q:[],onReady:function(g){k.q.push(g)}};e=b.createElement(h);e.async=1;e.src=f;f=b.getElementsByTagName(h)[0];f.parentNode.insertBefore(e,f)})(window,document,"script",a.scriptUrl,"DD_RUM");var c=Number(a.sessionReplaySampleRate),d=isNaN(c)?0:Math.min(100,Math.max(0,c));DD_RUM.onReady(function(){DD_RUM.init({clientToken:a.clientToken,
applicationId:a.appId,site:a.site,service:a.service,env:a.environment,version:"6.5.13",sampleRate:100,sessionReplaySampleRate:d,trackInteractions:!0,trackResources:!0,trackLongTasks:!0,defaultPrivacyLevel:"mask-user-input"});DD_RUM.startSessionReplayRecording();var k=DD_RUM.getInternalContext();k&&k.application_id||console.error("[Datadog] RUM failed to initialize. Check Client Token or App ID.")})}else console.warn("[Datadog] Missing required configuration. Skipping initialization.")}})();
(function(){let a=document.querySelector("meta[property\x3d'googlemaps']")?.dataset;void 0!==a&&(window.CHIPW=window.CHIPW||{},window.CHIPW.aemGoogleMapsConfig={dataKey:a.datakey,scriptBaseUrl:a.scriptbaseurl,appKey:a.appkey,correlationId:a.correlationid})})();
(function(){let a=document.querySelector("meta[property\x3d'mmd']")?.dataset;void 0!==a&&(window.CHIPW=window.CHIPW||{},window.CHIPW.MenuMetadataApiConfig={menuIngredientsEndpoint:a.ingredients,menuAllergenDietsEndpoint:a.allergens,menuInnovationOnlineMealsEndpoint:a.onlineMeal},window.CHIPW.chipotleServicesApiConfig={chipotleServicesBaseUrl:a.baseurl,chipotleServicesAppKey:a.appkey})})();
(function(){let a=document.querySelector("meta[property\x3d'rest']")?.dataset;void 0!==a&&(window.CHIPW.restaurantConfig={endpoint:a.endpoint,key:a.appkey})})();let deferredPrompt=null;
(function(){function a(){try{null!=deferredPrompt&&"true"!==localStorage.getItem("androidPrompted")&&(deferredPrompt.prompt(),deferredPrompt=null,localStorage.setItem("androidPrompted","true"))}catch(d){deferredPrompt=null}document.removeEventListener("click",a)}function c(d){deferredPrompt=null}document.addEventListener("click",a);window.addEventListener("beforeinstallprompt",d=>{d.preventDefault();deferredPrompt=d;deferredPrompt.userChoice.then(c)})})();
(function(){var a=document.querySelector("meta[property\x3d'chipotlegtm']")?.dataset;if(void 0!==a){var c=window;a=a.chipotlegtmId;c.dataLayer=c.dataLayer||[];c.dataLayer.push({"gtm.start":(new Date).getTime(),event:"gtm.js"});c=document.getElementsByTagName("script")[0];var d=document.createElement("script");d.async=!0;d.src="https://www.googletagmanager.com/gtm.js?id\x3d"+a;c.parentNode.insertBefore(d,c)}})();