# GENERATED by deploy-ssr.sh — built locally, nothing compiles here.
FROM node:24-alpine
WORKDIR /app
RUN addgroup -S -g 1001 nodejs && adduser -S -u 1001 -G nodejs site
COPY --chown=site:nodejs server.mjs sites.json ./
COPY --chown=site:nodejs sites/ ./sites/
USER site
EXPOSE 3000
ENV PORT=3000 HOSTNAME=0.0.0.0 SITES_ROOT=/app/sites SITES_CONFIG=/app/sites.json
HEALTHCHECK --interval=15s --timeout=3s --start-period=10s \
  CMD wget -qO- http://127.0.0.1:3000/_health >/dev/null || exit 1
CMD ["node", "server.mjs"]
