/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGeneratePurritoRouteImport } from './routes/api/generate-purrito'
import { Route as OrderPickupRouteImport } from './routes/order.$pickup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeneratePurritoRoute = ApiGeneratePurritoRouteImport.update({
  id: '/api/generate-purrito',
  path: '/api/generate-purrito',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderPickupRoute = OrderPickupRouteImport.update({
  id: '/order/$pickup',
  path: '/order/$pickup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/generate-purrito': typeof ApiGeneratePurritoRoute
  '/order/$pickup': typeof OrderPickupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/generate-purrito': typeof ApiGeneratePurritoRoute
  '/order/$pickup': typeof OrderPickupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/generate-purrito': typeof ApiGeneratePurritoRoute
  '/order/$pickup': typeof OrderPickupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/generate-purrito' | '/order/$pickup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/generate-purrito' | '/order/$pickup'
  id: '__root__' | '/' | '/api/generate-purrito' | '/order/$pickup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiGeneratePurritoRoute: typeof ApiGeneratePurritoRoute
  OrderPickupRoute: typeof OrderPickupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-purrito': {
      id: '/api/generate-purrito'
      path: '/api/generate-purrito'
      fullPath: '/api/generate-purrito'
      preLoaderRoute: typeof ApiGeneratePurritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$pickup': {
      id: '/order/$pickup'
      path: '/order/$pickup'
      fullPath: '/order/$pickup'
      preLoaderRoute: typeof OrderPickupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiGeneratePurritoRoute: ApiGeneratePurritoRoute,
  OrderPickupRoute: OrderPickupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
